apiVersion: v1
kind: Pod
metadata:
  labels:
    app: front
  name: front
spec:
  securityContext:
    runAsUser: 1000  
    runAsGroup: 1000
    fsGroup: 1000 
  containers:
  - image: alpine
    name: front
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
    command:
    - /bin/sh
    - -c
    - sleep 1d
